task: textvqa_val_noocr
test_split: validation
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: submission
    aggregation: !function utils.textvqa_aggreate_submissions
    higher_is_better: true
include: _default_template_textvqa_yaml
model_specific_prompt_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
    ocr: false
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"
